export const LOAD_CHARTS_SUCCESS = "LOAD_CHARTS_SUCCESS";
export const CREATE_CHART = "CREATE_CHART";
export const HANDLE_CHARTS_LOAD = "HANDLE_CHARTS_LOAD";
export const GET_EMBEDDED_REPORT = "GET_EMBEDDED_REPORT";
export const UPDATE_ACTIVE_PAGE_VISUALS = "UPDATE_ACTIVE_PAGE_VISUALS";
export const UPDATE_LAYOUT_COLUMNS = "UPDATE_LAYOUT_COLUMNS";
export const REMOVE_VISUAL_STATE = "REMOVE_VISUAL_STATE";
